# Generated by Django 5.0.3 on 2024-04-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mybio',
            new_name='user_bio',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='mytags',
            new_name='user_tags',
        ),
    ]
