# Generated by Django 5.0.3 on 2024-04-18 14:05

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_mybio_customuser_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='default_pp.jpg', upload_to=account.models.user_directory_path),
        ),
    ]
