# Generated by Django 5.0.3 on 2024-04-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_message_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room_name',
        ),
    ]
